# Generated by Django 3.0.1 on 2024-03-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20240312_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehistory',
            name='image_url',
            field=models.TextField(),
        ),
    ]
